import { createContext } from 'react';
import { buttonsNavigationTypes } from '../interfaces';

interface RecipesContext {
  fixedList: any[],
  setFixedList: (newState: any) => void,
  buttonsNavigation: any | buttonsNavigationTypes[],
  setButtonsNavigation: (newState: any | buttonsNavigationTypes[]) => void,
  foodId: any[],
  setFoodId: (newState: any) => void,
  drinkId: any[],
  setDrinkId: (newState: any) => void,
  buttons: any[],
  setButtons: (newState: any) => void,
  listApi: any[],
  setListApi: (newState: any) => void,
  filterCat: any[],
  setFilterCat: (newState: any) => void,
  objItem: any,
  setObjItem: (newState: any) => void,
  type: string,
  setType: (newState: string) => void,
  fav: any[],
  setFav: (newState: any) => void,
  link: string,
  setLink: (newState: any) => void,
  reqApiCategory: (category: string, type: string) => void,
  reqApiFId: (newState: any) => any,
  reqApiDId: (newState: any) => any,
  initialRequest: () => void,
  listAllDrinks: () => void,
  listAllFoods: () => void,
  isFav: (id: string) => boolean,
  addFavorites: (item: any) => void, 
  clickLink: (item: any) => void,
  getFavorites: () => void,
  createElement: (numState: any) => void,
  objIngrMeas: any,
  setObjIngrMeas: (numState: any) => void,
  objGeneralist: any,
  setObjGeneralist: (numState: any) => void,
}

const initialValue: RecipesContext = {
  fixedList: [],
  setFixedList: () => {},
  buttonsNavigation: [],
  setButtonsNavigation: () => {},
  foodId: [],
  setFoodId: () => {},
  drinkId: [],
  setDrinkId: () => {},
  buttons: [],
  setButtons: () => {},
  listApi: [],
  setListApi: () => {},
  filterCat: [],
  setFilterCat: () => {},
  objItem: {},
  setObjItem: () => {},
  type: '',
  setType: () => {},
  fav: [],
  setFav: () => {},
  reqApiCategory: () => {},
  reqApiFId: () => {},
  reqApiDId: () => {},
  initialRequest: () => {},
  listAllDrinks: () => {},
  listAllFoods: () => {},
  isFav: () => { return false },
  addFavorites: () => {},
  clickLink: () => {},
  link: '',
  setLink: () => {},
  getFavorites: () => {},
  createElement: () => {},
  objIngrMeas: {},
  setObjIngrMeas: () => {},
  objGeneralist: {},
  setObjGeneralist: () => {},
}

const contexto = createContext(initialValue);
export default contexto;

